spring.application.name=foro-hub-potaxiano

spring.datasource.url=jdbc:mysql://localhost/foro_hub_potaxiano
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.username = root
spring.datasource.password = ${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate

api.security.secret=${JWT_SECRET:123456}